-- Tōramally seed data. Import after schema.sql.
SET NAMES utf8mb4;

INSERT INTO settings (k,v) VALUES
('site_name','Tōramally'),
('site_url',''),
('whatsapp',''),
('phone',''),
('email_public',''),
('hours',''),
('announcement',''),
('address_store','Ground Floor, 26 Chakraberia Road N, Jadubabur Bazar, Bhowanipore, Kolkata 700020'),
('maps_url','https://www.google.com/maps/search/?api=1&query=Toramally+26+Chakraberia+Road+North+Bhowanipore+Kolkata'),
('instagram','https://www.instagram.com/houseoftoramally/'),
('facebook','https://www.facebook.com/toramally/'),
('business_name','House of Tōramally'),
('business_address','595-AA/050-A, Beside Olive Crown Hotel, 2nd Floor, Swaroop Chandra Khera, LDA Colony, Kanpur Road, Lucknow 226012'),
('business_state','Uttar Pradesh'),
('business_state_code','09'),
('gstin',''),
('gst_rate_low','5'),
('gst_rate_high','18'),
('gst_threshold','2500'),
('invoice_prefix','TM'),
('order_prefix','TM-'),
('commission_prefix','CM-'),
('currencies_json','{"INR": 1, "USD": 84, "GBP": 110, "EUR": 95, "AED": 23, "SGD": 64}'),
('rounding_json','{"INR": 1, "USD": 5, "GBP": 5, "EUR": 5, "AED": 10, "SGD": 5}'),
('commission_threshold','85000'),
('patron_rate','5'),
('ga_id',''),
('meta_pixel_id',''),
('seo_home_title','Tōramally | Bootmaker. Hand painted, tattooed and carved shoes'),
('seo_home_desc','Hand painted, tattooed and carved shoes, made by hand in Lucknow. Flagship in Kolkata.'),
('smtp_host',''),
('smtp_port','465'),
('smtp_secure','ssl'),
('smtp_user',''),
('smtp_pass_enc',''),
('mail_from',''),
('mail_from_name','Tōramally'),
('orders_alert_email','');

INSERT INTO collections (id,slug,type,name,scale_word,tagline,description,how_1,how_2,how_3,from_price,lead_weeks,buy_mode_note,on_ladder,sort) VALUES
(1,'velvet','craft','Velvet','Effortless','Soft, everyday','Velvet uppers for everyday ease, finished with a small leather patch, an all-over laser pattern, or a small hand-painted leather patch.','Velvet is cut and lasted on a light, cemented construction.','A calf patch is applied, lasered or painted by hand.','A soft pair made for daily wear, not for occasion.',8000,'2 to 4','Add to Bag',1,10),
(2,'patina','craft','Patina','Quiet','Colour, by hand','Instead of pre-coloured leather, colour is brushed onto calf one coat after another. The layers give a two-tone depth and the faint brush texture that is the house signature. The shine is built slowly with water and wax.','Crust calf is lasted in its natural state.','Dyes are brushed on by hand, layer over layer, heel and toe deepened.','Water and wax are worked in by hand until the toe holds a mirror shine.',16000,'4 to 6','Add to Bag',1,20),
(3,'scarring','craft','Scarring','Marked','Marked by light','Scarring (laser): the mark is made by removing, not adding. A beam lifts the surface of the calf in a precise pattern, which is then coloured and burnished so the design sits within the leather.','The pattern is drawn and set to the size of your pair.','The laser removes the finest layer of the grain.','The marked leather is patinated and polished by hand.',24000,'5 to 7','Add to Bag (House patterns); Commission (custom)',1,30),
(4,'miniature','craft','Miniature','Painted','Art, painted by hand','Miniature painting in the manner of the Lucknow and Mughal ateliers, applied directly to the finished shoe with fine brushes. Botanical borders, birds, the house fish. No two pairs are alike.','The leather is prepared and the design pencilled onto the vamp.','The artist paints in layers, the finest details with a single-hair brush.','The painting is sealed and the pair is polished around it.',23000,'6 to 8','Add to Bag (House artwork); Commission (custom)',1,40),
(5,'tattoo','craft','Tattoo','Expressive','Drawn by hand','Line work in the language of tattooing, worked into the leather by hand with a tattoo machine. Where Scarring is precise and geometric, Tattoo is the hand of the artist: ink, line and shading.','The design is stencilled onto the upper.','The artist inks the line work and shading by hand.','The ink is set and the leather finished and polished.',28000,'6 to 8','Add to Bag (House designs); Commission (custom)',1,50),
(6,'carving','craft','Carving','Sculpted','Leather, sculpted by hand','Relief carved and tooled into thick calf by hand. The most labour-intensive craft in the house: scales, paisleys and serpents raised from the surface, then coloured to deepen every cut.','A thicker calf is chosen and the design transferred.','Each line is cut, then bevelled and modelled to raise the relief.','Colour is worked into the cuts and the surface burnished.',69000,'10 to 14','Commission',1,60),
(7,'bespoke','craft','Bespoke','One of One','Made around you','Your silhouette, your colour, your artwork, your initials. A pair that exists once, made after a conversation, a design proof and your approval.','We talk: occasion, fit, ideas, references.','You approve a digital design proof and colour swatch.','The workshop makes the pair and sends photographs as it takes shape.',NULL,'8 to 14','Commission',1,70),
(8,'classics','collection','Classics',NULL,NULL,'The house''s permanent, signature designs.',NULL,NULL,NULL,NULL,NULL,NULL,0,80),
(9,'tattooed','collection','Tattooed',NULL,NULL,'Pairs with tattoo line work drawn by hand.',NULL,NULL,NULL,NULL,NULL,NULL,0,90),
(10,'hand-painted','collection','Hand Painted',NULL,NULL,'Patina and miniature, painted by hand.',NULL,NULL,NULL,NULL,NULL,NULL,0,100),
(11,'carved','collection','Carved',NULL,NULL,'Relief carved into leather by hand.',NULL,NULL,NULL,NULL,NULL,NULL,0,110),
(12,'miniatures','collection','Miniatures',NULL,NULL,'Miniature painting in the Lucknow manner.',NULL,NULL,NULL,NULL,NULL,NULL,0,120);

INSERT INTO products (id,slug,name,poetic,story,category,line,silhouette,last_name,craft_id,personalisation_level,construction,material,base_price,availability,lead_min,lead_max,buy_mode,occasions,size_type,featured,drawing_json,hsn_code,sort) VALUES
(1,'taus','Taus','A peacock in miniature, painted across the vamp.',NULL,'Men','Special Occasion','Belgian loafer','LOBO',4,'House Design','Blake stitched','Calf',23000,'Made to Order',5,7,'Add to Bag','Wedding,Evening','shoe_men',1,'{"shape": "loafer", "art": "peacock"}','6403',10),
(2,'noor','Noor','A backless Belgian, burnished to a quiet glow.',NULL,'Men','Classic','Mule','LOBO',2,'House Design','Blake stitched','Calf',16000,'Ready to Ship',5,7,'Add to Bag','Everyday','shoe_men',1,'{"shape": "mule"}','6403',20),
(3,'shaam','Shaam','Evening colour, layered by hand.',NULL,'Men','Classic','Belgian loafer','LOBO',2,'House Design','Blake stitched','Calf',18000,'Ready to Ship',5,7,'Add to Bag','Everyday,Evening','shoe_men',1,'{"shape": "loafer"}','6403',30),
(4,'adab','Adab','The Oxford, as the house first imagined it.',NULL,'Men','Classic','Oxford','RAY',2,'House Design','Goodyear welted','Calf',26000,'Made to Order',5,7,'Add to Bag','Everyday,Evening','shoe_men',1,'{"shape": "oxford"}','6403',40),
(5,'chaman','Chaman','A garden painted on a single piece of calf.',NULL,'Men','Special Occasion','Wholecut Oxford','Aziz',4,'House Design','Goodyear welted','Calf',33000,'Made to Order',6,8,'Add to Bag','Wedding,Statement','shoe_men',1,'{"shape": "wholecut", "art": "botanical"}','6403',50),
(6,'naqsh','Naqsh','A lattice lifted from the grain by light.',NULL,'Men','Classic','Penny loafer','031',3,'House Design','Blake stitched','Calf',28000,'Made to Order',5,7,'Add to Bag','Everyday,Statement','shoe_men',0,'{"shape": "penny"}','6403',60),
(7,'siyahi','Siyahi','Ink line work across the quarter, drawn by hand.',NULL,'Men','Special Occasion','Derby','054',5,'House Design','Goodyear welted','Calf',32000,'Made to Order',6,8,'Add to Bag','Statement,Evening','shoe_men',1,'{"shape": "derby", "art": "mandala"}','6403',70),
(8,'nag','Nāg','A serpent raised from the leather, scale by scale.',NULL,'Men','Special Occasion','Adelaide Oxford','714',6,'One of One','Goodyear welted','Calf',69000,'Commission',10,14,'Commission','Statement','shoe_men',0,'{"shape": "adelaide", "art": "snake"}','6403',80),
(9,'darbar','Darbar','A court of flowers and birds, painted end to end.',NULL,'Men','Special Occasion','Belgian loafer','LOBO',4,'Bespoke','Blake stitched','Calf',85000,'Commission',10,12,'Commission','Wedding','shoe_men',0,'{"shape": "loafer", "art": "botanical"}','6403',90),
(10,'rukhsat','Rukhsat','For the groom, the Peshawari in burnished tan.',NULL,'Men','Special Occasion','Peshawari','LOBO',2,'House Design','Blake stitched','Calf',20000,'Made to Order',4,6,'Add to Bag','Wedding','shoe_men',0,'{"shape": "mule"}','6403',100),
(11,'gulnar','Gulnār','A kitten heel with a pomegranate bloom.',NULL,'Women','','Heel',NULL,4,'House Design','Cemented','Calf',24000,'Made to Order',5,7,'Add to Bag','Wedding,Evening','shoe_women',0,'{"shape": "heel", "art": "botanical"}','6403',110),
(12,'mehr','Mehr','A flat mule marked in a fine lattice.',NULL,'Women','','Mule',NULL,3,'House Design','Cemented','Calf',18000,'Ready to Ship',4,6,'Add to Bag','Everyday','shoe_women',0,'{"shape": "mule"}','6403',120),
(13,'zoya','Zoya','A soft flat, painted at the toe.',NULL,'Women','','Flat',NULL,4,'House Design','Cemented','Calf',16500,'Made to Order',4,6,'Add to Bag','Everyday,Wedding','shoe_women',0,'{"shape": "flat", "art": "botanical"}','6403',130),
(14,'makhmal','Makhmal','Velvet for every day, with a small leather patch.',NULL,'Everyday','','Loafer',NULL,1,'House Design','Cemented','Velvet',8500,'Ready to Ship',2,4,'Add to Bag','Everyday','shoe_men',1,'{"shape": "slipper"}','6403',140),
(15,'aaram','Ārām','A house slipper, as it should be.',NULL,'Everyday','','Slipper',NULL,1,'House Design','Cemented','Velvet',5500,'Ready to Ship',2,3,'Add to Bag','Everyday','shoe_men',0,'{"shape": "slipper"}','6403',150),
(16,'kamar','Kamar','A patina belt to match your pair.',NULL,'Accessories','','Belt',NULL,2,'Personalised','Hand stitched','Calf',9500,'Made to Order',3,4,'Add to Bag','Everyday','belt',0,'{"shape": "belt"}','4203',160),
(17,'batua','Batua','A billfold with tattoo line work on the face.',NULL,'Accessories','','Wallet',NULL,5,'House Design','Hand stitched','Calf',7500,'Ready to Ship',3,4,'Add to Bag','Everyday','none',0,'{"shape": "wallet", "art": "mandala"}','4202',170),
(18,'pebble','Tōramally Pebble','A small painted keepsake from the workshop.',NULL,'Accessories','','Collectible',NULL,4,'House Design',NULL,'Calf',4500,'Ready to Ship',2,3,'Add to Bag','Everyday','none',0,'{"shape": "pebble", "art": "mahi"}','9701',180),
(19,'shoe-shine-service','The Shoe Shine Service','Cleaned, fed and polished by hand, and returned.','Cleaning, conditioning, fresh laces where needed, and a hand-built polish to the toe and heel. For any brand of good leather shoes. Send your pairs to the Kolkata house or bring them in. We confirm by WhatsApp when they are ready.','Service','','Service',NULL,2,'House Design',NULL,'Calf',1500,'Ready to Ship',1,2,'Add to Bag','','none',0,'{"shape": "loafer"}','9997',190);

INSERT INTO product_colours (id,product_id,name,hex,sort) VALUES
(1,1,'Oxblood','#4b1719',0),
(2,1,'Black','#1f1c19',1),
(3,1,'Navy','#1e2b45',2),
(4,2,'Cognac','#8f4b21',0),
(5,2,'Tobacco','#6a4528',1),
(6,2,'Black','#1f1c19',2),
(7,3,'Burgundy','#5e1f2c',0),
(8,3,'Oxblood','#4b1719',1),
(9,3,'Forest Green','#26412f',2),
(10,3,'Navy','#1e2b45',3),
(11,4,'Black','#1f1c19',0),
(12,4,'Dark Brown','#3c2619',1),
(13,4,'Oxblood','#4b1719',2),
(14,5,'Tobacco','#6a4528',0),
(15,5,'Ivory','#e9e0cc',1),
(16,5,'Black','#1f1c19',2),
(17,6,'Dark Brown','#3c2619',0),
(18,6,'Black','#1f1c19',1),
(19,6,'Cognac','#8f4b21',2),
(20,7,'Tan','#a66e3d',0),
(21,7,'Cognac','#8f4b21',1),
(22,7,'Beige','#c9b28f',2),
(23,8,'Cognac','#8f4b21',0),
(24,8,'Dark Brown','#3c2619',1),
(25,9,'Ivory','#e9e0cc',0),
(26,9,'Beige','#c9b28f',1),
(27,10,'Tan','#a66e3d',0),
(28,10,'Cognac','#8f4b21',1),
(29,10,'Ivory','#e9e0cc',2),
(30,11,'Ivory','#e9e0cc',0),
(31,11,'Black','#1f1c19',1),
(32,11,'Burgundy','#5e1f2c',2),
(33,12,'Black','#1f1c19',0),
(34,12,'Tan','#a66e3d',1),
(35,12,'Beige','#c9b28f',2),
(36,13,'Beige','#c9b28f',0),
(37,13,'Ivory','#e9e0cc',1),
(38,13,'Navy','#1e2b45',2),
(39,14,'Forest Green','#26412f',0),
(40,14,'Navy','#1e2b45',1),
(41,14,'Burgundy','#5e1f2c',2),
(42,14,'Black','#1f1c19',3),
(43,15,'Navy','#1e2b45',0),
(44,15,'Burgundy','#5e1f2c',1),
(45,16,'Tan','#a66e3d',0),
(46,16,'Dark Brown','#3c2619',1),
(47,16,'Black','#1f1c19',2),
(48,16,'Oxblood','#4b1719',3),
(49,17,'Tan','#a66e3d',0),
(50,17,'Cognac','#8f4b21',1),
(51,17,'Black','#1f1c19',2),
(52,18,'Oxblood','#4b1719',0),
(53,18,'Forest Green','#26412f',1),
(54,18,'Ivory','#e9e0cc',2),
(55,19,'Black','#1f1c19',0);

INSERT INTO product_stock (product_id,colour_id,size,qty) VALUES
(2,NULL,'UK 8',2),
(2,NULL,'UK 9',2),
(2,NULL,'UK 10',2),
(3,NULL,'UK 7',2),
(3,NULL,'UK 8',2),
(3,NULL,'UK 9',2),
(12,NULL,'UK 4',2),
(12,NULL,'UK 5',2),
(12,NULL,'UK 6',2),
(14,NULL,'UK 7',2),
(14,NULL,'UK 8',2),
(14,NULL,'UK 9',2),
(14,NULL,'UK 10',2),
(15,NULL,'UK 7',2),
(15,NULL,'UK 8',2),
(15,NULL,'UK 9',2),
(15,NULL,'UK 10',2),
(15,NULL,'UK 11',2),
(17,NULL,'One size',2),
(18,NULL,'One size',2);

INSERT INTO product_collection (product_id,collection_id) VALUES
(1,10),
(1,12),
(1,4),
(2,8),
(2,10),
(2,2),
(3,8),
(3,10),
(3,2),
(4,8),
(4,10),
(4,2),
(5,10),
(5,12),
(5,4),
(6,8),
(6,3),
(7,9),
(7,5),
(8,11),
(8,6),
(9,10),
(9,12),
(9,4),
(10,10),
(10,2),
(11,10),
(11,12),
(11,4),
(12,3),
(13,10),
(13,12),
(13,4),
(14,1),
(15,1),
(16,10),
(16,2),
(17,9),
(17,5),
(18,10),
(18,12),
(18,4),
(19,10),
(19,2);

INSERT INTO press_items (name,note,kind,sort) VALUES
('Lakmé Fashion Week','The house debuted at Summer/Resort 2018 with hand-welted shoes, belts and wallets.','event',10),
('The Shoe Snob','Reviewed the hand-welted construction and the tattooed, hand-painted and carved finishes.','press',20),
('Shoes & Accessories','Profiled the house as a pioneer of tattooed and hand-painted leather footwear in India.','press',30),
('Aashni + Co','Stockist. Hand-painted mules, loafers and occasion footwear.','stockist',40),
('Aza Fashions','Stockist. Men''s occasion and classic footwear.','stockist',50),
('Tata CLiQ Luxury','Stockist. Designer leather shoes and loafers.','stockist',60);

INSERT INTO journal_posts (slug,category,title,dek,body_html,craft_id,status,published_at) VALUES
('what-is-scarring','Craft','What is scarring?','A mark made by taking away, not adding.','<p>Most decoration on a shoe is added: paint, stitching, a buckle. Scarring works the other way round. A beam of light lifts the finest layer of the grain, and the pattern that remains is part of the leather itself.</p><p>In the workshop the design is drawn first, then scaled to the size of your pair so that the lattice meets the seams where it should. After the laser comes the part that makes it a Tōramally: the marked calf is patinated by hand, so colour settles deeper into the scarred lines and the pattern reads in two tones.</p><p>Scarring is often confused with our Tattoo craft. They are different. Scarring is precise and geometric, made by light. Tattoo is drawn by hand, line by line, with ink.</p><p>Care is simple: a neutral cream, a soft brush, and a patient polish. Avoid heavy coloured polish, which can fill the finer lines.</p>',3,'Published',NOW()),
('the-art-of-patina','Craft','The art of patina','Colour, one coat after another.','<p>Rather than cutting a shoe from leather that arrives already coloured, we begin with calf in its natural state and bring the colour by hand.</p><p>Dye is brushed on in thin layers. Heel and toe are taken deeper than the waist, which gives the pair its shadow and shape. The brush leaves a faint texture that we keep on purpose. It is the signature of a hand at work.</p><p>Then comes the shine. Water and wax are worked in by hand, layer upon layer, until the toe holds a mirror. It takes hours, and it cannot be hurried.</p><p>Because the colour is built rather than printed, a patina pair can be taken darker later. Bring it to the house and we can deepen it for you.</p>',2,'Published',NOW()),
('why-handmade-shoes-take-weeks','Stories','Why handmade shoes take weeks','Time is part of the process.','<p>A made-to-order Tōramally usually takes five to seven weeks. Painted and tattooed pairs take a little longer, carved pairs longer still.</p><p>The time is spent where you can see it. The upper is lasted and left to take its shape. Welted pairs are stitched by hand to the welt and then to the sole. The waist is shaped. Colour is layered and allowed to rest between coats. A miniature painting is built up over days.</p><p>We would rather tell you honestly how long a pair takes than hurry it. When a date matters, such as a wedding, tell us early and we will plan the making around it.</p>',4,'Published',NOW()),
('choosing-wedding-shoes-for-the-groom','Style','Choosing wedding shoes for the groom','Begin with the date, then the silhouette.','<p>Start with time. A made-to-order pair needs five to eight weeks; a commission with custom artwork needs ten or more. Our wedding date check will tell you what is possible.</p><p>Then the outfit. A sherwani or achkan sits well with a Peshawari, a Belgian loafer or a mule. A bandhgala suit can take a wholecut Oxford.</p><p>Finally, how much of yourselves goes into the pair. Initials, the wedding date inside the heel, a family motif, or a miniature painted to match the embroidery. Matching belts and pairs for the family can be made at the same time.</p>',4,'Published',NOW()),
('what-is-a-belgian-loafer','Craft','What is a Belgian loafer?',NULL,NULL,NULL,'In preparation',NULL),
('what-is-leather-tattooing','Craft','What is leather tattooing?',NULL,NULL,NULL,'In preparation',NULL),
('from-miniature-painting-to-leather','Craft','From miniature painting to leather',NULL,NULL,NULL,'In preparation',NULL),
('why-no-two-hand-painted-shoes-are-alike','Craft','Why no two hand-painted shoes are alike',NULL,NULL,NULL,'In preparation',NULL),
('the-anatomy-of-a-toramally-shoe','Craft','The anatomy of a Tōramally shoe',NULL,NULL,NULL,'In preparation',NULL),
('how-to-care-for-patina-leather','Craft','How to care for patina leather',NULL,NULL,NULL,'In preparation',NULL);

INSERT INTO pages (slug,title,body_html) VALUES
('privacy','Privacy Policy','<p>We collect only what you give us: your name and contact details when you create an account, enquire, book or order, and the details of your pair. We use them to make and deliver your order, to reply to you, and, if you agree, to send Letters from the House.</p><p>We do not sell your data. Card and UPI details are entered on our payment partner''s secure page and never reach our servers. You can ask us to see, correct or delete your data at any time by writing to us.</p><p>We follow India''s Digital Personal Data Protection Act, 2023 and, for visitors from Europe, the GDPR.</p>'),
('terms','Terms & Conditions','<p>Prices are set in INR and shown in other currencies from a fixed table reviewed monthly. An order is confirmed when payment is received and the house confirms it. Estimated prices for custom work become final when confirmed in writing.</p><p>Made-to-order and commissioned pairs are made individually; lead times are estimates and we will keep you informed.</p>'),
('shipping','Shipping Policy','<p>Domestic delivery across India and international delivery by insured courier. Ready-to-ship pairs leave the house within a few working days; made-to-order pairs ship when finished.</p><p>International clients pay import duties on delivery; we share an estimate before you confirm. Tracking is sent by email and is visible in My Account.</p>'),
('returns','Return & Exchange Policy','<p>Ready-to-ship pairs, unworn and in the box, can be exchanged for size within 7 days of delivery. Personalised, made-to-order and commissioned pairs are made for you and are not returnable. If there is a fault in the making, we remake the pair.</p>'),
('cookies','Cookie Policy','<p>We store your bag, currency and builder progress in your browser. Analytics and advertising tags load only if you accept them.</p>');

INSERT INTO content_blocks (page,block_key,data_json,sort) VALUES
('home','hero','{"title": "Crafted in silence.", "text": "Hand painted, tattooed and carved shoes, made by hand in our Lucknow workshop.", "cta1": "Discover the collection", "cta2": "Commission your pair", "caption": "Taus, Belgian loafer. Miniature, painted by hand.", "product": "taus"}',10),
('home','house','{"title": "A house that happens to make shoes.", "text": "Tōramally joins Lucknow''s refinement to Kolkata''s artistic spirit. Our shoes are made in a small workshop, cut from calf, coloured by hand, and finished with painting, tattoo, scarring or carving by the artisans who own each craft.\\n\\nThe house began with hand-welted shoes, belts and wallets at Lakmé Fashion Week in 2018, and was among the first in India to tattoo and hand-paint leather footwear."}',20),
('home','ladder','{"title": "The craft ladder", "text": "Seven levels of hand. Each step asks a little more of the artisan, and gives a little more of you to the pair."}',30),
('home','shop','{"title": "Shop"}',40),
('home','signature','{"title": "Signature pairs", "text": "Ready to ship, or made to order in weeks."}',50),
('home','bespoke','{"title": "Made for you.", "text": "You do not simply choose a Tōramally. You decide how much of yourself goes into it."}',60),
('home','wedding','{"title": "Made for the day you remember.", "text": "Pairs for the groom, the bride, and the family. Initials, the date inside the heel, a family motif, or a miniature painted to match the embroidery."}',70),
('home','press','{"title": "Press and stockists"}',80),
('home','making','{"title": "The making", "text": "The macro is the proof. Brush, beam, needle and blade."}',90),
('home','visit','{"title": "Visit the house in Kolkata."}',100);

INSERT INTO payment_gateways (code,name,region,display_label,sort) VALUES
('razorpay','Razorpay','domestic','UPI, cards, netbanking and wallets',10),
('payu','PayU','domestic','UPI, cards and netbanking',20),
('ccavenue','CCAvenue','both','Cards, UPI and netbanking',30),
('stripe','Stripe','international','International cards',40),
('paypal','PayPal','international','PayPal and international cards',50);

INSERT INTO shipping_rates (scope,name,rate_inr,free_above_inr,eta_text,sort) VALUES
('domestic','Insured delivery within India',0,NULL,'3 to 6 working days after dispatch',10),
('international','Insured international courier',3500,NULL,'5 to 10 working days after dispatch',20);
